name: CI

on:
  push:
    branches:
      - 'main'
      - 'renovate/**'
  pull_request:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      # disabled steps for now
      # - run: yarn lint
      # - run: yarn test
